name: Deploy pages
permissions: 
  contents: write
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy.yml
      - slides.md
      - public
      - package.json
      - package-lock.json
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.tool-versions'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx slidev build
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
